[features]
seeds = false
skip-lint = false
[programs.localnet]
perpetuals = "3LjnwXNbvUe9DB2qaTNvCL4sVvtvshCEeydhzUfkbJTB"
[programs.devnet]
perpetuals = "3LjnwXNbvUe9DB2qaTNvCL4sVvtvshCEeydhzUfkbJTB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/maxq/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 programs/perpetuals/tests/anchor/*.ts"
